Html&css file
QueenterJuma/Hello---Microverse pull request #1
Opened 2022-10-26 09:21 UTC by QueenterJuma

2022-10-26 12:33 UTC, BregornOriginal requested changes
Hi @QueenterJuma , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

✔️ Linters are passing
✔️ Good commit history
✔️ Files HTML and CSS are present
✔️ Uses the correct template of README
✔️ Correct use of GitHub Flow

## Required Changes ♻️ ♻️ ♻️

![the-simpsons-homer-simpson](https://user-images.githubusercontent.com/28307960/157369993-50d5ba12-099f-4f2a-9a19-5e57ee2d1c96.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 20:08 UTC, mckent05 requested changes
Hi @QueenterJuma,

# STATUS: CHANGES REQUIRED ♻️  

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!
![almost there](https://user-images.githubusercontent.com/73607512/198126567-a6444791-5f8b-4419-bbc2-fd8b3c4df451.gif)

## Highlights
- All linters are passing correctly ✔️ ✔️ 
- GitHub flow correctly used 👏 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-26 20:08 UTC, mckent05 commented on A.html
> +</html>
**OPTIONAL** - In order to make your repo look professional, naming conventions are very important. I'd suggest you give this file a better name, so as to make it easily readable. In this context, I suggest you use `index.html` 😄 😄

2022-10-26 20:08 UTC, mckent05 commented on A.css
> +}
- As the previous reviewer suggested, it is very important that your PR summary and PR title are descriptive, this will make it easy for viewers to understand what your PR is about and the changes made. I'd suggest you include (edit) the PR summary by clicking on the 3 dots highlighted in the image attached by the previous reviewer  👍 👍 

OPTIONAL - In order to make your repo look professional, naming conventions are very important. I'd suggest you give this file a better name, so as to make it easily readable. In this context, I suggest you use `styles.css` 😄 😄

2022-10-27 09:08 UTC, QueenterJuma commented
## What does this PR do?
This PR is raised to set up a Hello Microverse Project
## Description of the task to be completed
- [ ] Create a new GitHub repository
- [ ] Create a new branch according to Github flows
- [ ] Add .gitignore file
- [ ] Set up a linter for CSS and HTML files
- [ ] Ignore test.md and node_modules files
- [ ] Set up a linter for HTM, CSS files 
- [ ] Add README file
- [ ] Add three files each in a separate commit

1.  HTML file with text "Hello Microverse" using h1 tag

2.CSS file with the class of favorite color of the heading

3 test.md file with the text "This file should be ignored by git"

##How should it be tested
Clone the repository
````
git clone https://github.com/QueenterJuma/Hello---Microverse/pull/1
````
Navigate to the folder
````
cd
````
Checkout  the branch
````
git checkout the branch_name
````
#### Thanks for reviewing my PR.

2022-10-27 14:55 UTC, Qoosim requested changes
#   *Status: Required Changes* :recycle: 

Hi @QueenterJuma, 

Great work on making the changes requested by the previous reviewers 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

-    No linter errors. :heavy_check_mark: 
-    Good README file. :heavy_check_mark: 
-    Correct GitHub Flow. :heavy_check_mark: 

![](https://user-images.githubusercontent.com/95297251/191952218-b7185270-c02b-4e4d-89af-eae77fcd8bea.gif)
 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 14:55 UTC, Qoosim commented on index.css
> +}
- [OPTIONAL] I can see that this class name does not exist in your `h1` element. Where is it coming from. You're supposed to give your `h1` inside the index.html this class name and then use it here to style the content of `h1` tag. Kindly look into this and fix it.

2022-10-27 14:55 UTC, Qoosim commented on index.html
> +</body>
- [OPTIONAL] It is required to give your `h1` element a class name and then use that class name to style the content of the element. Kindly add a class name to your `h1` element and use the class name to style its content.

2022-10-27 14:55 UTC, Qoosim commented on .gitignore
> +node_modules
- [ ] Your test.md file still appears on your repository. Kindly follow these two articles to rectify the issue. Follow this [article](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) to untrack the file from commit and follow this [article](https://www.freecodecamp.org/news/gitignore-file-how-to-ignore-files-and-folders-in-git/) to add both your folder and file to the `.gitignore` and then commit the changes and push.

2022-10-27 20:54 UTC, ridwanediallo approved these changes
# STATUS: APPROVED 🟢
## Hi @QueenterJuma , 
![Congratulations!GIF](https://user-images.githubusercontent.com/55918904/191301390-43d62dfa-bfdc-49c5-943b-4d72f4ea5bb8.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- GitHub flow is used correctly. ✔
- All linters checks are ok. ✔

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 23:29 UTC, merged